<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      decorations.urdf.xacro
\authors   Paul Bovbel <pbovbel@clearpathrobotics.com>, Devon Ash <dash@clearpathrobotics.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="propbot_decorations" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- 
  ***********************************************************************************************
  Propbot Decoration
  ***********************************************************************************************
  The chassis and sensors are considered "decorations" on the base_link. A macro is defined below
  to execute this decoration in one step in `propbot.urdf.xacro`
  -->
  <xacro:macro name="propbot_decorate">

    <!-- 
    Chassis
    ======================================================================
    -->
    <!-- Spawn Propbot chassis -->
    <link name="chassis_link">
      <visual>
        <origin xyz="${base_x_size/2} 0 ${2*wheel_vertical_offset - base_z_size}" rpy="${M_PI/2} 0 ${-M_PI/2}" />
        <geometry>
          <mesh filename="package://propbot_description/meshes/propbot_chassis.STL" />
        </geometry>
      </visual>
    </link>

    <!-- Set chassis colour in Gazebo -->
    <gazebo reference="chassis_link">
      <material>Gazebo/Red</material>
    </gazebo>

    <!-- Attach chassis to the robot -->
    <joint name="chassis_joint" type="fixed">
      <parent link="base_link" />
      <child link="chassis_link" />
    </joint>

    <!-- 
    Top plate
    ======================================================================
    A tiny plate use to link the sensors to the robot
    -->
    <xacro:if value="$(optenv PROPBOT_TOP_PLATE_ENABLED true)">
      <!-- Spawn the top plate -->
      <link name="top_plate_link">
        <visual>
          <origin xyz="${base_x_size/2} ${-base_y_size/2 + 0.027} ${top_plate_height}" rpy="0 0 0" />
          <geometry>
            <box size="0.01 0.01 0.001"/>
          </geometry>
          <material name="wheel_material">
				    <color rgba="0.25 0.25 0.75 0" />
      		</material>
        </visual>
      </link>
      <!-- Attach top plate to chassis -->
      <joint name="top_plate_chassis_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="top_plate_link"/>
        <origin xyz="0 ${top_plate_front - base_y_size/8} 0.001" rpy="0 0 0"/>
      </joint>
    </xacro:if>

  </xacro:macro>

</robot>
