<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      propbot.urdf.xacro
\authors   Paul Bovbel <pbovbel@clearpathrobotics.com>, Devon Ash <dash@clearpathrobotics.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<!-- NOTES

* All values are in metric (m, kg)
* Specific robot structure values extracted from URDF exported from Solidworks

-->
<robot name="propbot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- 
  ***********************************************************************************************
  Default Spawn Settings
  ***********************************************************************************************
  -->
  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="spawn_lat" default="49.9" />
  <xacro:arg name="spawn_long" default="8.9" />

  <!-- 
  ***********************************************************************************************
  Base Size Specifications
  ***********************************************************************************************
  The "shadow" of the robot
  -->
  <xacro:property name="base_x_size" value="0.9820" /> <!-- x is front to back -->
  <xacro:property name="base_y_size" value="0.8278" /> <!-- y is side to side -->
  <xacro:property name="base_z_size" value="0.1369" /> <!-- height of the bottom battery plate from the ground -->

  <!-- 
  ***********************************************************************************************
  Misc. Constants
  ***********************************************************************************************
  -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- 
  ***********************************************************************************************
  Laser and Camera Args
  ***********************************************************************************************
  -->
  <xacro:arg name="laser_enabled" default="false" />
  <xacro:arg name="laser_xyz" default="$(optenv PROPBOT_VLP-16_XYZ 0.08 ${-base_y_size/2 + 0.0516/2} 0.925)" /> <!-- note: base_y_size/2 + lidar radius -->
  <xacro:arg name="laser_rpy" default="$(optenv PROPBOT_VLP-16_RPY 0 0 0)" />

  <xacro:arg name="rgbd_camera_enabled" default="false" />
  <xacro:arg name="rgbd_camera_xyz" default="$(optenv PROPBOT_REALSENSE_XYZ 0 0 0.225)" />
  <xacro:arg name="rgbd_camera_rpy" default="$(optenv PROPBOT_REALSENSE_RPY 0 0.18 0)" />

  <!-- 
  ***********************************************************************************************
  Included URDF/XACRO Files 
  ***********************************************************************************************
  -->
  <xacro:include filename="$(find propbot_description)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find propbot_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find propbot_description)/urdf/passive_wheel.urdf.xacro" />
  <xacro:include filename="$(find propbot_description)/urdf/accessories/realsense_d435.urdf.xacro"/>
  <xacro:include filename="$(find propbot_description)/urdf/accessories/sensor_arch.urdf.xacro"/>
  <xacro:include filename="$(find propbot_description)/urdf/accessories/VLP-16_mount.urdf.xacro"/>
  
  <!-- 
  ***********************************************************************************************
  Mass and Inertial Values and Scaling
  ***********************************************************************************************
  Values as reported by SolidWorks
  -->
  <!-- Approximate REAL robot mass -->
  <xacro:property name="robot_mass" value="70.0"/>   

  <!-- SW reported mass values -->
  <xacro:property name="base_link_mass" value="0.96268" />
  <xacro:property name="chassis_mass" value="19.52246"/>  
  <xacro:property name="wheel_mass" value="2.96542"/>  

  <!-- Base link inertia-->
  <xacro:property name="base_ixx" value="0.083320" />
  <xacro:property name="base_ixy" value="-1.882647E-14" />
  <xacro:property name="base_ixz" value="2.527076E-19" />
  <xacro:property name="base_iyy" value="0.003905" />
  <xacro:property name="base_iyz" value="7.039418E-19" />
  <xacro:property name="base_izz" value="0.087218" />

   <!-- Chassis link inertia-->
  <xacro:property name="chassis_ixx" value="0.42226" />
  <xacro:property name="chassis_ixy" value="0.00028" />
  <xacro:property name="chassis_ixz" value="-0.00012" />
  <xacro:property name="chassis_iyy" value="0.46973" />
  <xacro:property name="chassis_iyz" value="0.00017" />
  <xacro:property name="chassis_izz" value="0.16238" />

  <!-- Robot frame mass scale factor: use to scale chassis and base link masses and inertial values -->
  <xacro:property name="frame_msf" value="${robot_mass/chassis_mass}" />  
  <!-- Wheel mass scale factor: use to scale wheel masses and inertial values -->
  <xacro:property name="wheel_msf" value="${1}" />

  <!-- 
  ***********************************************************************************************
  Wheel Properties and Mounting Specifications 
  ***********************************************************************************************
  -->
  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.08975" />
  <xacro:property name="wheel_radius" value="0.127" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheel_to_wheel" value="0.400" /> <!-- distance between wheel axles -->
  <xacro:property name="track" value="0.9198" /> <!-- y wheel distance, wheel central point to central point -->
  <xacro:property name="wheel_vertical_offset" value="${wheel_radius}" /> <!-- axle to ground distance -->
  <xacro:property name="wheel_central_offset" value="0.0533" /> <!-- offset from the center -->

  <!-- 
  ***********************************************************************************************
  Sensor Mounting Specifications
  ***********************************************************************************************
  -->
  <xacro:property name="top_plate_height" value="${0.24845 + wheel_radius}" /> <!-- height from the ground to the top plate -->
  <xacro:property name="top_plate_front" value="${base_x_size/2}" /> <!-- distance from the origin to the front of the robot -->

  <!-- 
  ***********************************************************************************************
  Linking and Joint Specification
  ***********************************************************************************************
  The various links and joints are created and put together
  -->

  <!-- 
  Base Link
  ======================================================================
  -->
  <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_z_size}" rpy="0 0 ${-M_PI/2}" />
      <geometry>
        <mesh filename="package://propbot_description/meshes/propbot_base_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${wheel_central_offset + wheel_length/2} ${base_z_size/4}" rpy="0 0 ${-M_PI/2}" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
  </link>

  <!-- Set base_link colour in Gazebo -->
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- 
  Inertial Link
  ======================================================================
  Interial link stores the robot's inertial information 
  For this case, the mass, origin, and inertia values of the main chassis is used
  -->
  <link name="inertial_link">
    <inertial>
      <mass value="${(chassis_mass + base_link_mass) * frame_msf}"/>
      <origin xyz="0 0 0.42243" rpy = "${-M_PI/2} ${-M_PI/2} 0" />
      <inertia 
        ixx="${(base_ixx + chassis_ixx) * frame_msf}" 
        ixy="${(base_ixy + chassis_ixy) * frame_msf}" 
        ixz="${(base_ixz + chassis_ixz) * frame_msf}" 
        iyy="${(base_iyy + chassis_iyy) * frame_msf}" 
        iyz="${(base_iyz + chassis_iyz) * frame_msf}" 
        izz="${(base_izz + chassis_izz) * frame_msf}" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- 
  IMU Link
  ======================================================================
  IMU Link is the standard mounting position for the UM6 IMU.
  Can be modified with environment variables in /etc/ros/setup.bash 
  -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="$(optenv PROPBOT_IMU_XYZ 0.19 0 0.149)" rpy="$(optenv PROPBOT_IMU_RPY 0 -1.5708 3.1416)" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link">
  </gazebo>

  <!-- 
  Wheels
  ======================================================================
  -->
  <!-- Right -->
  <xacro:propbot_wheel wheel_prefix="front_right">
    <origin xyz="${track/2} ${-wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_wheel>
  <xacro:propbot_wheel wheel_prefix="rear_right">
    <origin xyz="${-track/2 + (2/3)*wheel_radius} ${-wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_wheel>
  <!-- Left -->
  <xacro:propbot_wheel wheel_prefix="front_left">
    <origin xyz="${track/2} ${wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_wheel>
  <xacro:propbot_wheel wheel_prefix="rear_left">
    <origin xyz="${-track/2 + (2/3)*wheel_radius} ${wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_wheel>

  <!-- Middle (passives) -->
  <xacro:propbot_passive_wheel wheel_prefix="left">
    <origin xyz="0 ${wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_passive_wheel>
  <xacro:propbot_passive_wheel wheel_prefix="right">
    <origin xyz="0 ${-wheel_to_wheel} ${wheel_vertical_offset}" rpy="0 0 ${-M_PI/2}" />
  </xacro:propbot_passive_wheel>

  <!-- Decorate the robot -->
  <xacro:propbot_decorate />

  <!-- 
  Laser and Camera
  ======================================================================
  -->
  <xacro:if value="$(arg laser_enabled)">

    <VLP-16_mount prefix="base" />

    <joint name="laser_mount_joint" type="fixed">
      <origin xyz="$(arg laser_xyz)" rpy="$(arg laser_rpy)" />
      <parent link="top_plate_link" />
      <child link="base_laser_mount" />
    </joint>
  </xacro:if>

  <xacro:if value="$(arg rgbd_camera_enabled)">

    <xacro:sensor_arch prefix="" parent="top_plate_link">
      <origin xyz="${base_x_size/2 - 0.05} ${-base_y_size/2 + 0.025} 0.6" rpy="0 0 0"/>
    </xacro:sensor_arch>

    <realsense_d435 name="camera" parent="sensor_arch_mount_link">
      <origin xyz="$(arg rgbd_camera_xyz)" rpy="$(arg rgbd_camera_rpy)" robot_namespace="$(arg robot_namespace)"/>
     </realsense_d435>
  </xacro:if>

  <!-- 
  ***********************************************************************************************
  Gazebo Specifications
  ***********************************************************************************************
  -->
  <!-- Motion controller -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
    </plugin>
  </gazebo>

  <!-- IMU controller -->
  <gazebo>
    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>50.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>imu/data</topicName>
      <accelDrift>0.005 0.005 0.005</accelDrift>
      <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
      <rateDrift>0.005 0.005 0.005 </rateDrift>
      <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
      <headingDrift>0.005</headingDrift>
      <headingGaussianNoise>0.005</headingGaussianNoise>
    </plugin>
  </gazebo>

  <!-- GPS controller -->
  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>40</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>$(arg spawn_lat)</referenceLatitude>
      <referenceLongitude>$(arg spawn_long)</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>

</robot>