controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.3 # A tolerance on the goal point for the planner.

DWAPlannerROS:
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.2
  max_vel_x: 20.0
  max_rot_vel: 10.0
  acc_lim_x: 20.0

  holonomic_robot: false