controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.3 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:

  # Frames

  odom_topic: /odometry/filtered
  map_frame: odom
      
  # Trajectory
    
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  allow_init_with_backwards_motion: false  # Forward motion only to start
      
  # Robot
          
  max_vel_x: 2.0
  max_vel_x_backwards: 0.3
  max_vel_theta: 4.0
  acc_lim_x: 0.3
  acc_lim_theta: 1.0
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "point"  # Uses the least computational power

  # Goal Tolerance
      
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.25
  free_goal_vel: false
      
  # Obstacles
      
  min_obstacle_dist: 1.0
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5

  # Optimization
      
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  alternative_time_cost: false # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: false  # Save processing power by making this false
